# Generated by Django 5.1.15 on 2026-06-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0037_rename_beginner_activity_types"),
        ("submissions", "0012_activityprogress_audio_edit_history_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["assignment", "-submitted"],
                name="submissions_assignm_06178b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submissionattachment",
            index=models.Index(
                fields=["submission", "-submitted"],
                name="submissions_submiss_b947e9_idx",
            ),
        ),
    ]
