# Generated by Django 5.1.15 on 2026-06-27 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0039_backfill_course_assignments"),
        ("courses", "0007_data_migration_stress_test_course"),
        ("instruments", "0006_delete_instrumentconfig"),
        ("musics", "0028_partinstrumentsample"),
        ("submissions", "0013_submission_submissions_assignm_06178b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="course_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="assignments.courseassignment",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.instrument",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="musics.part",
            ),
        ),
    ]
