# Generated by Django 5.1.15 on 2026-06-27 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0039_backfill_course_assignments"),
        ("courses", "0007_data_migration_stress_test_course"),
        ("submissions", "0015_backfill_submission_course_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityprogress",
            name="course_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_progress",
                to="assignments.courseassignment",
            ),
        ),
        migrations.AddField(
            model_name="activityprogress",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.enrollment",
            ),
        ),
    ]
