# Generated by Django 5.1.15 on 2026-06-27 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0039_backfill_course_assignments"),
        ("submissions", "0017_backfill_activity_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityprogress",
            name="assignment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_progress",
                to="assignments.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="assignments.assignment",
            ),
        ),
    ]
