# Generated by Django 5.1.15 on 2026-06-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0040_courseassignment_instrument"),
        ("courses", "0007_data_migration_stress_test_course"),
        ("submissions", "0018_alter_activityprogress_assignment_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="activityprogress",
            constraint=models.UniqueConstraint(
                fields=("course_assignment", "enrollment"),
                name="unique_activity_progress",
            ),
        ),
    ]
