# Generated by Django 5.1.15 on 2026-06-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0041_remove_assignment_activity_and_more"),
        ("courses", "0007_data_migration_stress_test_course"),
        ("instruments", "0006_delete_instrumentconfig"),
        ("musics", "0028_partinstrumentsample"),
        ("submissions", "0019_activityprogress_unique_activity_progress"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="submission",
            name="submissions_assignm_06178b_idx",
        ),
        migrations.RemoveField(
            model_name="activityprogress",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="assignment",
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["course_assignment", "enrollment", "-submitted"],
                name="submissions_course__a8fa9d_idx",
            ),
        ),
    ]
