# Generated by Django 3.2.11 on 2024-03-13 03:21

from django.db import migrations


def add_demos(apps, schema_editor):
    """Intentionally a no-op (was: seed demo NEA courses + assignments).

    The original migration imported the LIVE ``teleband.courses.helper.assign_piece_plan``
    and live model classes and called them to create demo assignments. Importing live
    app code into a data migration makes a fresh ``migrate`` depend on the *current*
    schema and helper behavior: as the models and assign helpers evolve (notably the
    Phase 2 CourseAssignment remodel), this historical migration would run new code
    against the old, frozen schema and break the build. We already hit a variant of this
    when a ``select_related("user")`` in the helper selected ``users.external_id`` before
    that column's migration had run.

    The demo data is non-essential convenience seed -- no test, fixture, or schema depends
    on it -- so the seeding is removed and this migration no longer references app code.
    Databases that already applied the original migration are unaffected; only fresh
    migrates (tests, CI, new deploys) skip the demo seeding.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0032_auto_20240311_1235"),
        ("users", "0007_user_instrument"),
        ("courses", "0006_course_can_edit_instruments"),
        ("instruments", "0004_instrument_midi_program_number"),
    ]

    operations = [
        migrations.RunPython(add_demos, migrations.RunPython.noop),
    ]
