# Generated by Django 5.1.15 on 2026-06-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0037_rename_beginner_activity_types"),
        ("courses", "0007_data_migration_stress_test_course"),
        ("musics", "0028_partinstrumentsample"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assignments.activity",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_assignments",
                        to="courses.course",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="musics.piece"
                    ),
                ),
                (
                    "piece_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assignments.pieceplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_assignments",
                        to="assignments.courseassignment",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.enrollment",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="assignments.assignmentgroup",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="courseassignment",
            index=models.Index(
                fields=["course", "piece"], name="assignments_course__c52c53_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseassignment",
            constraint=models.UniqueConstraint(
                fields=("course", "activity", "piece"), name="unique_course_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupassignment",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "course_assignment"),
                name="unique_group_assignment",
            ),
        ),
    ]
