# Generated by Django 5.1.15 on 2026-06-28 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0039_backfill_course_assignments"),
        ("instruments", "0006_delete_instrumentconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassignment",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.instrument",
            ),
        ),
    ]
