# Generated by Django 5.1.15 on 2026-06-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0040_courseassignment_instrument"),
    ]

    operations = [
        # Drop the unique constraint first: it references (activity, enrollment,
        # piece), and SQLite's table-remake during RemoveField would otherwise try
        # to recreate it against already-removed fields.
        migrations.RemoveConstraint(
            model_name="assignment",
            name="unique_assignment",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="enrollment",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="group",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="instrument",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="part",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="piece",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="piece_plan",
        ),
    ]
