# Generated by Django 5.1.15 on 2026-06-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0041_remove_assignment_activity_and_more"),
        (
            "submissions",
            "0020_remove_submission_submissions_assignm_06178b_idx_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
